services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  bloggonbian:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - .:/bloggonbian
    ports:
      - "3000:3000"
    depends_on:
      - db

  bloggonbian-swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: bloggonbian-swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./document/reference/unified.yaml:/app.yaml
    environment:
      SWAGGER_FILE: /app.yaml
    init: true

  bloggonbian-swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: bloggonbian-swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./document/reference/unified.yaml:/app.yaml
    environment:
      SWAGGER_JSON: /app.yaml
    init: true
